[role="mt-4"]
== Introduction

The Cookie Consent Modules for J1 Theme create a BS Modal-based dialog
complient to the GDPR rules given by the EU government. The dialog is
placed at the top of the website to show and select cookies settings and
provides buttons to accept and decline and to show policy privacy settings.

Once a user has made the decision to either accept or decline, the Cookie Consent
slides up, then disappears. The Cookie Consent can be set up to work in a variety
of ways. By default, it uses assumed consent. This means that when a user
visits the website, cookies can be set as normal with no interruption.

The Cookie Consent is still displayed to provide the user with options for cookies.
It can also be set up to assume refusal. So when a user visits the website,
until they press the accept button on the Cookie Consent, no cookies should be set.

You can specify which buttons show on the Cookie Consent. The default is to show
the accept and privacy policy buttons and no decline button. This way,
assumed consent is used, and the user cannot opt out of cookies. If the user
is unhappy about the use of cookies, they can simply leave the website.

The Cookie Consent is also very easy to style. There are just 9 lines of CSS code
in total. Changing the heights, widths, background colours, etc. is very
quick and easy meaning it can fit in with the website design and colour
scheme.

=== Installing

To start, download the zip file containing the Cookie Consent plugin, a CSS file
and example HTML document. Upload the javascript and CSS files to your website
and add them between your head tags. Make sure to download the latest version
of jQuery if your website does not already include it.

You will also need to initialise the Cookie Consent, which can be done with the
following code (Make sure if you already use $(document).ready() that you
only copy what you need of below so you don't have too many
$(document).ready()'s).

[source, js]
----
  $(document).ready(function(){
    $.cookieBar();
  });
----

Refresh your website, and the Cookie Consent should appear! A basic setup may
look like the following:

[source, html]
----
  <script type="text/javascript" src="/your-js-folder/jquery.js"></script>
  <script type="text/javascript" src="/your-js-folder/jquery.cookiebar.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
       $.cookieBar();
    });
  </script>
----

=== Disabling Cookies

If a user chooses to disable cookies (If you give them that option), you
need to make sure that scripts such as Google Analytics need to be disabled.

This can be done by wrapping the code in a simple if statement.

[source, js]
----
  if(jQuery.cookieBar('cookies')){
    //Google Analytics or other code here
  }
----
