
This library enables the automatic resizing of the height and width of
both same and cross domain iFrames to fit their contained content. It
provides a range of features to address the most common issues with
using iFrames, these include:

* Height and width resizing of the iFrame to content size.
* Works with multiple and nested iFrames.
* Domain authentication for cross domain iFrames.
* Provides a range of page size calculation methods to support complex
CSS layouts.
* Detects changes to the DOM that can cause the page to resize using
https://developer.mozilla.org/en/docs/Web/API/MutationObserver[MutationObserver].
* Detects events that can cause the page to resize (Window Resize, CSS
Animation and Transition, Orientation Change and Mouse events).
* Simplified messaging between iFrame and host page via
https://developer.mozilla.org/en-US/docs/Web/API/window.postMessage[postMessage].
* Fixes in page links in iFrame and supports links between the iFrame
and parent page.
* Provides custom sizing and scrolling methods.
* Exposes parent position and viewport size to the iFrame.
* Provides `onMouseEnter` and `onMouseLeave` events for the iFrame.
* Works with http://viewerjs.org/[ViewerJS] to support PDF and ODF
documents.



== Getting Started

=== Install

This package can be installed via NPM
(`npm install iframe-resizer --save`).

=== Usage

The package contains two minified JavaScript files in the
https://github.com/davidjbradshaw/iframe-resizer/tree/master/js[js]
folder. The first
(https://raw.githubusercontent.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.min.js[iframeResizer.min.js])
is for the page hosting the iFrames. It can be called with via
JavaScript:

[source,js]
----
const iframes = iFrameResize( [{options}], [css selector] || [iframe] );
----

The second file
(https://raw.github.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js[iframeResizer.contentWindow.min.js])
needs placing in the page(s) contained within your iFrame. This file is
designed to be a guest on someone else’s system, so has no dependencies
and won’t do anything until it’s activated by a message from the
containing page.

=== Typical setup

The normal configuration is to have the iFrame resize when the browser
window changes size or the content of the iFrame changes. To set this up
you need to configure one of the dimensions of the iFrame to a
percentage and tell the library to only update the other dimension.
Normally you would set the width to 100% and have the height scale to
fit the content.

[source,html]
----
<style>
  iframe {
    width: 1px;
    min-width: 100%;
  }
</style>
<script src="/js/iframeResizer.min.js"></script>
<iframe id="myIframe" src="http://anotherdomain.com/iframe.html"></iframe>
<script>
  iFrameResize({ log: true }, '#myIframe')
</script>
----

*Note:* Using _min-width_ to set the width of the iFrame, works around
an issue in iOS that can prevent the iFrame from sizing correctly.

If you have problems, check the
https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/troubleshooting.md[troubleshooting]
section.

=== Example

To see this working take a look at this
https://davidjbradshaw.github.io/iframe-resizer/example/[example] and
watch the
https://developer.mozilla.org/en-US/docs/Tools/Web_Console[console].

== API Documentation

IFrame-Resizer provides an extensive range of options and APIs for both
the parent page and the iframed page.

* *Parent Page API*
** https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md[Options]
** https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/events.md[Events]
** https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/methods.md[Methods]
* *IFramed Page API*
** https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/options.md[Options]
** https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/events.md[Events]
** https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/methods.md[Methods]
* *Use with Libraries and Frameworks*
** https://github.com/davidjbradshaw/iframe-resizer-react[React]
** https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/use_with/vue.md[Vue]
** https://github.com/davidjbradshaw/iframe-resizer/issues/831#issuecomment-665760332[Nuxt]
** https://github.com/davidjbradshaw/iframe-resizer/issues/478#issuecomment-347958630[Angular]
** https://github.com/alexlafroscia/ember-iframe-resizer-modifier[Ember]
** https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/use_with/jquery.md[jQuery]
** https://stackoverflow.com/a/65724113/2087070[Google Apps Script]
* https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/troubleshooting.md[Troubleshooting]
* https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/upgrade.md[Upgrade
from version 3]
* https://github.com/davidjbradshaw/iframe-resizer/blob/master/CHANGELOG.md[Version
history]

== License

Copyright © 2013-23 https://github.com/davidjbradshaw[David J. Bradshaw]
- Licensed under the link:LICENSE[MIT License]
