== Library Features

This library uses **vanilla JavaScript**. It is less than 400 bytes of
CSS and about 4Kb of JavaScript (minified and gzipped). The only
dependency this script has is
https://github.com/cferdinandi/smooth-scroll[Smooth Scroll] (which has
no dependencies).

This script works in **all modern browsers and IE 7+**.

=== Initialization

==== CSS load

CSS is used for expanding & collapsing groupings and some basic styling.

[source, html]
----
<link rel="stylesheet" href="/assets/css/tocbot.css">
----

==== JS load

Include the script at the bottom of the page before the closing body
tag.

[source, html]
----
<script src="/assets/js/tocbot.js"></script>
----


==== JS initialization

Initialize the script

[source, js]
----
tocbot.init({
  // Where to render the table of contents.
  tocSelector: '.js-toc',
  // Where to grab the headings to build the table of contents.
  contentSelector: '.js-toc-content',
  // Which headings to grab inside of the contentSelector element.
  headingSelector: 'h1, h2, h3',
});
----

If content in the div has changed then trigger a refresh (optionally
with new options).

[source, js]
----
tocbot.refresh();
----

=== Options

==== tocSelector

==== headingSelector

==== ignoreSelector

==== contentSelector

==== activeLinkColor

==== collapseDepth

==== headingsOffset

==== throttleTimeout

==== includeHtml

==== scrollOptions

==== easing

==== offset

==== speed

==== updateURL



=== Callbacks

No callbacks or events.

=== Methods


==== .init

Initialize tocbot with an options object.

[source, js]
----
tocbot.init(options)
----

==== .destroy

Destroy tocbot and remove event listeners.

[source, js]
----
tocbot.destroy()
----

==== .refresh

Refresh tocbot if the document changes and it needs to be rebuilt.

[source, js]
----
tocbot.refresh()
----

